### ISSUE TITLE
Plugins don't work when following instructions

### ISSUE THREAD

**Issue by mehlon** [ItsDeidara/MegaNTR#22]
Because the folder names are the titles, rather than the game id's, simply putting the `plugins` folder onto the root of the SD card doesn't work. Thankfully because of the convenient folder structure, all it took is a script to fix this: `for i in *; do a=$(find "$i"/*.plg -type f -printf "%f\n" | sed -e 's/\.plg$//'); mv "$i" "$a"; done`.

**Comment by StonedModder** [comment]
I'd be open to a pull request with this fix as I am no longer maintaining this since I moved from the 3ds to other projects
