### ISSUE TITLE
Screen flashing after launching plugin for New super Mario bros 2 EU. message "next time use fair plugin"

### ISSUE THREAD

**Issue by yacsama** [ItsDeidara/MegaNTR#24]
The plugin works but the screen is flickering in red with a message "next time use fair plugin"
New super Mario bros 2 EU.
Does anyone know how to fix this?

**Comment by StonedModder** [comment]
That error means that you have more than one plugin installed for this game

**Comment by yacsama** [comment]
Thank you very much.
It works now after I kept one .pkg on the folder.
