### ISSUE TITLE
Plugin for Pokemon Super Mystery Dungeon on Cheats menu but not in plugins

### ISSUE THREAD

**Issue by anon332** [ItsDeidara/MegaNTR#27]
Hi, so after browsing the files I noticed that the codes for pokemon: Super Mystery Dungeon were in the cheats folder, though not in the plugins folder for use. Any way to fix/change this? Thanks!

**Comment by StonedModder** [comment]
If you rename the cheats folder to cheats, and install ctrpluginframework, you should be able to get around this. The txt file with the codes however need to correspond to the correct title ID https://gbatemp.net/threads/ctrpluginframework-blank-plugin-now-with-action-replay.487729/
