### ISSUE TITLE
How to use Super Smash Bros character mod?

### ISSUE THREAD

**Issue by kokichioumalovesme** [ItsDeidara/MegaNTR#36]
I can’t find the button to modify characters anywhere. What menu is it in and what button do I press?

**Comment by kokichioumalovesme** [comment]
Update: None of the cheats are working for me

**Comment by realMBite** [comment]
This same issue has happened to me. I researched it, and apparently, you need a New3DS or higher to get cheats to work on Super Smash Bros. Certain games need more power from the device, so it shuts out all other processes (this explains why it says "Please wait..." and the screen turns black after closing one of them).

**Comment by kokichioumalovesme** [comment]
I have a new 3DS. The menu loads up fine, I turn the cheats on just fine, and nothing works. For example I press L for infinite gold and it doesn’t do anything

**Comment by kokichioumalovesme** [comment]
Basically I’m just asking what the controls are to trigger each cheat because none of them are working simply by enabling them

**Comment by realMBite** [comment]
Oh, sorry. I was thinking of the menu wasn't working. I don't have a New3DS so I can't relate, but my best guess is that the cheats are broken.

**Comment by kokichioumalovesme** [comment]
I see. That’s a shame. I’ll try to look into it a bit more but you’re probably right
