### ISSUE TITLE
No folder named plugin

### ISSUE THREAD

**Issue by SnowWraith200** [ItsDeidara/MegaNTR#39]
I tired to get a plugin for Monster Hunter 4 Ultimate but my micro SD doesn't have a floder named plugin.

**Comment by FantashiS** [comment]
You have to create a new folder call "plugin" yourself.

**Comment by SnowWraith200** [comment]
thanks for that i got it all set up i thinks. do you know where i have to go for the menu to activate the cheats?

**Comment by FantashiS** [comment]
do you have bootntr selector installed? If you don't, follow the instructions online to install it. Then you can press X+Y in game to pop up the menu to use the code. However,  some code have to use specific button combinations to activate, you will find it by reading the description of the code which you want to use.

**Comment by SnowWraith200** [comment]
Thanks man have a nice day Sent from Mail for Windows 10 From: FantashiSSent: Tuesday, 28 April 2020 9:57 PMTo: ItsDeidara/MegaNTRCc: SnowWraith200; AuthorSubject: Re: [ItsDeidara/MegaNTR] No folder named plugin (#39) do you have bootntr selector installed? If you don't, follow the instructions online to install it. Then you can press X+Y in game to pop up the menu to use the code. However, some code have to use specific button combinations to activate, you will find it by reading the description of the code which you want to use.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by SnowWraith200** [comment]
Sorry just wanted to make sure.I have boot NTR installed and when I open it, it gives me a choice: 3.2, 3.3, 3.6Do you know witch one I should use if so it would help allotBecause I pressed X+Y but nothing happened except pulling out my weapon.Please help Sent from Mail for Windows 10 From: FantashiSSent: Tuesday, 28 April 2020 9:57 PMTo: ItsDeidara/MegaNTRCc: SnowWraith200; AuthorSubject: Re: [ItsDeidara/MegaNTR] No folder named plugin (#39) do you have bootntr selector installed? If you don't, follow the instructions online to install it. Then you can press X+Y in game to pop up the menu to use the code. However, some code have to use specific button combinations to activate, you will find it by reading the description of the code which you want to use.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by SnowWraith200** [comment]
Sorry just wanted to make sure.
I have boot NTR installed and when I open it, it gives me a choice: 3.2, 3.3, 3.6
Do you know witch one I should use if so it would help allot
Because I pressed X+Y but nothing happened except pulling out my weapon.
Please help

**Comment by SnowWraith200** [comment]
okay i thinks something changed because the bottom screen turns white with small black writing when  i press X+Y. When i press A on process Manager it just gives me a bunch of 8 digit codes and as far as i can tell none of them does anything. It just says : "Dump" and "info" but noting happens no matter what i do I've pressed every possible button combo i could think of but nothing works.
