### ISSUE TITLE
x99 item/equip/tech doesn't work

### ISSUE THREAD

**Issue by RazorDerment** [ItsDeidara/MegaNTR#42]
I tried to use the code for 99 equipment abd it doesn't work.
C0000000 000003F5
287E8B19 00000063
DC000000 00000001
D1000000 00000000
I put the code here. If is there a code for equipment please let me know.

**Comment by StonedModder** [comment]
Unfortunately, this project is more of an archive now. That being said, if you have the time, knowhow and would like to make a new code. I would be happy to accept a pull request!
